### PR TITLE
feat: upgrade to angular 15/16

### PR DESCRIPTION
**Pull request by lehoffma**
Hey! First of all thanks for the package, it has served us well over the past few years :)

However, with Angular's newest update to v16, the legacy `ngcc` compiler has been completely removed, resulting in this package sadly not working with our configuration anymore. Since there have been quite a lot of breaking changes and changes in how libraries are supported in Angular (with the CLI now using `ng-packagr` under the hood and multi-project workspaces becoming the norm), we decided it was easier to do a full breaking update to not just the dependencies, but also the structure of it all, which this PR is the result of. What that means specifically is:

- We moved everything into a CLI-generated monorepo-style workplace (with `angular-gauge` and `demo` as the two projects)
- We removed the custom webpack configurations, instead completely relying on the Angular CLI 
- We replaced the 3rd testing party libraries like `sinon` and `chai` with equivalent `jasmine` functions that Angular now provides out of the box
- The package now requires at least Angular v15 (but 16 has also been tested and works)

We published this version publicly as `@avtest/angular-gauge@^5.0.0` ([on npm](https://www.npmjs.com/package/@avtest/angular-gauge)), for those who just want to use it now. 

Let me know if we can do anything else to help in the merging process!

### CODE REVIEW

**Review by mattlewis92 — APPROVED** [review]
This is awesome, thank you so much for taking this on!!

**Comment by mattlewis92** [comment]
Released as [5.0.0](https://github.com/mattlewis92/angular-gauge/releases/tag/v5.0.0)! 🥳

**Comment by lehoffma** [comment]
Amazing, thank you so much for merging and releasing this so quickly! 🥳

**Comment by itsmehrd** [comment]
I am facing this error while `npm start` in Angular 15 application.
FYI, I installed using `npm i --legacy-peer-deps @avtest/angular-gauge@^5.0.0`

```
Error: node_modules/@avtest/angular-gauge/lib/gauge.component.d.ts:79:80 - error TS2344: Type '{ dialStartAngle: { alias: "dialStartAngle"; required: false; }; dialEndAngle: { alias: "dialEndAngle"; required: fals
e; }; dialRadius: { alias: "dialRadius"; required: false; }; min: { alias: "min"; required: false; }; ... 10 more ...; animationDuration: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"dialStartAngle"' is incompatible with index signature.
    Type '{ alias: "dialStartAngle"; required: false; }' is not assignable to type 'string'.

79     static ɵcmp: i0.ɵɵComponentDeclaration<GaugeComponent, "mwl-gauge", never, { "dialStartAngle": { "alias": "dialStartAngle"; "required": false; }; "dialEndAngle": { "alias": "dialEndAngle"; "required": false
; }; "dialRadius": { "alias": "dialRadius"; "required": false; }; "min": { "alias": "min"; "required": false; }; "max": { "alias": "max"; "required": false; }; "label": { "alias": "label"; "required": false; }; "c
olor": { "alias": "color"; "required": false; }; "showValue": { "alias": "showValue"; "required": false; }; "gaugeClass": { "alias": "gaugeClass"; "required": false; }; "dialClass": { "alias": "dialClass"; "requir
ed": false; }; "valueDialClass": { "alias": "valueDialClass"; "required": false; }; "valueClass": { "alias": "valueClass"; "required": false; }; "value": { "alias": "value"; "required": false; }; "animated": { "al
ias": "animated"; "required": false; }; "animationDuration": { "alias": "animationDuration"; "required": false; }; }, { "gaugeCreated": "gaugeCreated"; }, never, never, false, never>;
```

image

**Pull request merged**
